CREATE TABLE IF NOT EXISTS `Players` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(50) NOT NULL,
  `home_world` VARCHAR(30) NOT NULL,
  `discord_id` VARCHAR(30) NULL,
  `first_seen` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP(),
  `vip_tier` INT(11) NOT NULL DEFAULT 0,
  `vip_expiration` DATETIME NULL,
  `vip_balance` INT(11) NOT NULL DEFAULT 0,
  `notified` TINYINT(1) NOT NULL DEFAULT 0
  PRIMARY KEY (`id`)
) ENGINE=InnoDB AUTO_INCREMENT=148 DEFAULT CHARSET=utf8mb3;
